# Site settings
name: 赱乂的博客
email: 18738529936@163.com
author: zhq
url: https://blog.csdn.net/u014653854
resume_site: https://blog.csdn.net/u014653854
github: https://github.com/18738529936/
baseurl: ''
description: Actually, less is more!
meta_description: zhq;个人博客
motto: 士不可以不弘毅，任重而道远。
banner: 赱乂的博客

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 18738529936

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

